### ISSUE TITLE
Support for iterable versions of the standard calls.

### ISSUE THREAD

**Issue by BAXTER001** [superfell/Beatbox#21]
I have a small collection of monkey patches I put into our internal version of beatbox to add methods that return iterators for the collection returning calls that wrap the need to use queryMore, and alternate forms of upsert,insert and delete that take generators and chunk them into blocks of size batchSize.

How would you feel about a PR for adding these methods onto the Client or an iterClient subclass?

**Comment by superfell** [comment]
Sounds like a good idea.

**Comment by BAXTER001** [comment]
Cool, I'll submit a PR for an iterableClient subclass shortly.
