### ISSUE TITLE
init of beatbox.Client() 

### ISSUE THREAD

**Issue by mikegedelman** [superfell/Beatbox#23]
Have to use `beatbox._beatbox.Client()` to get a client.

Reproduced on Windows running Python 2.7.9, Ubuntu running Python 2.7.6, beatbox v32.1 on both, installed via pip.

```
>>> import beatbox
>>> svc = beatbox.Client()

Traceback (most recent call last):
  File "<pyshell#44>", line 1, in <module>
    svc = beatbox.Client()
AttributeError: 'module' object has no attribute 'Client'
>>> svc = beatbox._beatbox.Client() #This works
>>> 
```

**Comment by BAXTER001** [comment]
I assume you did a "pip install beatbox" that's an old unsupported fork.
