### ISSUE TITLE
Query Time Out

### ISSUE THREAD

**Issue by isherwoodTC** [superfell/Beatbox#24]
I keep getting a Query Time Out error when trying to bring back the whole table of "Case History" not sure if the api used in Beatbox is not the right place. Do I need to investigate the bulk api? Or another way to troubleshoot?

**Comment by superfell** [comment]
Are you getting a clientside HTTP timeout, or a query timeout error from salesforce?

**Comment by isherwoodTC** [comment]
from salesforce

On Mon, Aug 3, 2015 at 6:00 PM, Simon Fell <notifications@github.com> wrote:

> Are you getting a clientside HTTP timeout, or a query timeout error from
> salesforce?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/superfell/Beatbox/issues/24#issuecomment-127427217>.
>



-- 
*Ian Sherwood*
Trunk Club, Inc.* |* Business Intelligence Developer
325 West Ohio Street
Chicago, Illinois 60654
________________________
[image: Trunk Club Logo]

**Comment by superfell** [comment]
You should contact sfdc support, this could be a number of different issues and they have option to help address it.
