### ISSUE TITLE
can't select fields which contains the word 'Address'

### ISSUE THREAD

**Issue by itaygalea** [superfell/Beatbox#27]
Hello,
When I'm trying to pull Address fields (ShippingAddress, BillingAddress, Address etc.) from any table in Salesforce I run into an error in function query in module python_client (the failure is in function _extractRecord which is being called by function query). 

Is that a known issue? Is it because of the name Address? How should I pull those fields? 
Thanks a lot in advance! 
Itay

**Comment by superfell** [comment]
There is no _extractRecord in this version of Beatbox, I'm guessing you're using some other fork.
