### ISSUE TITLE
support in setting the batchSize of the service

### ISSUE THREAD

**Issue by itaygalea** [superfell/Beatbox#28]
Hello,
Is it possible to update the batchsize attribute of the service? 
In addition I've noticed that in some tables (Oportunity,Task) the chunk size is different than the default value 500 and the data is being pulled in chunks of 200. Can it be changed?

Thanks,
Itay

**Comment by superfell** [comment]
You can set the batchSize property on the client to change the default of 500.  Note that the server treats this as a hint only, you may get smaller batches than asked for based on the number and types of fields selected in the query.
