### ISSUE TITLE
How to pull the data from method describeGlobal()

### ISSUE THREAD

**Issue by itaygalea** [superfell/Beatbox#29]
Hi,

What is the required namespace for retrieving the returned objects from this method?
When I try the following (as explained in http://www.pocketsoap.com/beatbox/) :
sf = beatbox._tPartnerNS
svc = beatbox.Client()
svc.login(username, password)
res_tables = svc.describeGlobal()
tables_list = res_tables[sf.types:]

I don't get any results in tables_list. 
Should I address another field in sf? 

Thanks in advance! 
Itay

**Comment by superfell** [comment]
See the describeGlobal example in demo.py

	def describeGlobal(self):
		print "\ndescribeGlobal"
		dg = svc.describeGlobal()
		for t in dg[sf.sobjects:]:
			print str(t[sf.name]) + " \t " + str(t[sf.label])

the partner wsdl describes exactly what fields are available for each SObject returned.

I'll update the example on the website.
