### ISSUE TITLE
OS X El Capitan and TLS 1.0 error after updating openssl

### ISSUE THREAD

**Issue by doodlebro** [superfell/Beatbox#30]
Hi, I have followed your instructions in the readme for the TLS 1.0 abandonment... After checking that my python version is 2.7.10 and upgrading openssl to version 1.0.2g I am still receiving a TLS connection error on authentication.

I also tried the fix detailed here: https://urllib3.readthedocs.io/en/latest/security.html#pyopenssl but it did not affect anything.

Any help is appreciated.

**Comment by superfell** [comment]
run this in a terminal to show what OpenSSL library python is using, what does it show ?

python -c "import ssl; print ssl.OPENSSL_VERSION"

**Comment by doodlebro** [comment]
Thanks, this led me to the right place. Had to fix a bit of nonsense in my $PATH and reinstalled python to use the latest version of openssl.
