### ISSUE TITLE
gzipRequest not working for python3 

### ISSUE THREAD

**Issue by zli25** [superfell/Beatbox#46]
The default gzipRequest is set to True, but it doesn't work in python3. Got an error **TypeError: string argument expected, got 'bytes'** when executing `self.fileobj.write(b'\037\213'` in file gzip.py.

In python3, BytesIo should be used instead of StringIO, and thus a potential fix would be changing `self.__buf = StringIO("")` to `self.__buf = BytesIO(b"")` in file beatbox.py at line 283

**Comment by superfell** [comment]
Its using BytesIO, see https://github.com/superfell/Beatbox/blob/master/beatbox/_beatbox.py#L319 I suspect you either have out of date code, or are using one of the forks.

**Comment by zli25** [comment]
Thanks for the prompt reply. I installed this package via pip install, but it seems that I am using out of date code. Wonder if I can install this updated version using pip. Thanks!
