### ISSUE TITLE
Salesforce Refresh Instances

### ISSUE THREAD

**Issue by avivnoy** [superfell/Beatbox#49]
Salesforce going to do overall change at the 3rd of Dec
what they called - Refresh Instances.

Is it going to affect the use of Beatbox?
Do we need to change of upgrade something>

Thanks!

**Comment by alanjcastonguay** [comment]
https://help.salesforce.com/articleView?id=Instance-Refresh-Maintenance-FAQ&language=en_US&type=1

Instance refresh can cause urls to change. Beatbox and pyforce use the hostname login.salesforce.com, so shouldn’t be impacted.

**Comment by hynekcer** [comment]
I confirm that the hostname for Beatbox is updated by login. It depends on your application how long it holds the same login session how long it holds the same login session. It is usually at every request or more smart when the session expires (after a specific exception with login and retry) in high traffic application. The result for Beatbox is similar.

Some applications use the hostname for a link on a private web page or in a web service. If the application has been ever tested .e.g. with sandbox then it it sure that the hostname is nowhere hardcoded. In the worst case, the application need to be restarted after instance refresh to fix that functionality that doesn't depend on Beatbox.

**Comment by avivnoy** [comment]
We authenticate with user+password+token.
And beside that - use Beatbox as a blackbox :)
We not setting nothing in the UR and if i understand you correctly is supposed 
to be update automatically right ?

So beside generate new token for the api application, Is there something else?

**Comment by hynekcer** [comment]
Yes, everything will be updated automatically.

**Comment by avivnoy** [comment]
Is it required to re-install Beatbox with a new version?

**Comment by superfell** [comment]
No
