### ISSUE TITLE
Will beatbox support uploads to sfdc Files?

### ISSUE THREAD

**Issue by gtangthousandeyes** [superfell/Beatbox#50]
I just came across this https://www.salesforceben.com/rip-notes-attachments-say-hello-to-files/ and I was wondering if the existing beatbox `create` method will support the new SFDC Files. The article says that sfdc will be sunsetting Notes & Attachments in the near future

**Comment by superfell** [comment]
Looks like [Files is using the ContentDocument](https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_objects_contentdocument.htm?search_text=files) sobject, in which case it should already work fine with Beatbox.
