### ISSUE TITLE
No longer outputting json like legacy 2.7 version

### ISSUE THREAD

**Issue by thegreatstorm** [superfell/Beatbox#52]
I'm currently in transition changing our code from 2.7 to 3.7 and I found that beatbox required an update. I updated, it and fixed the calls, but now I'm getting response of a full string, instead of a json list. I use to have a code that did this.

row = {}
response = json.dumps(response)
jsonParser = json.loads(response)
row['Status'] = "Success"
row['IDNumber'] = jsonParser["IDNumber"]

But looks like the output is only showing only full string plus a true boolean at the front of it. 
I looked at issue 51, and attempted using the code given by superfell, but the sorting of the columns was completely out of wack, rec[0] had true,rec[1] were empty, and rec[2] had the full string, rec[3] had the third column, rec[4] had the 4th column.

FullString example output:
AccountIDAccountNameIDNumberStatus

**Comment by superfell** [comment]
Can you post the code where you're actually using Beatbox? Do you know which exact version you were on before? is it possible you were using one of the forks? (see #43 for more details)

**Comment by thegreatstorm** [comment]
Sure, I can't give you the exact code due to privacy reasons, but I'll make a example of the code, that is doing exactly what the old code did, and the new code did. I apologies for the privacy and delay of the response.
