### ISSUE TITLE
Getting more results than 500

### ISSUE THREAD

**Issue by thegreatstorm** [superfell/Beatbox#53]
I attempted to increase the batchsize, but I'm trying to get all the values since the values could increase or decreased based on he batch size. I attempted to use queryAll or querymore. But they both failed. I also attempted to use the following documentation, but doesn't seem to function with this version of beatbox. Can you provide me some insight on how I can get all the rows to show up. 
http://tomhayden3.com/2013/08/04/salesforce-python/

**Comment by simon-4242** [comment]
The [export.py](https://github.com/superfell/Beatbox/blob/master/examples/export.py) sample shows usage of queryMore.
