### ISSUE TITLE
Version of Beatbox in Pypi is incorrect?

### ISSUE THREAD

**Issue by idbentley** [superfell/Beatbox#6]
The version of Beatbox in Pypi is 20.0 http://pypi.python.org/pypi/beatbox/20.0

The version in this repository is 0.94.

The code seems to have been heavily re factored between these two versions.

The code within 20.0 hsa a copyright of 2006, while the one here is from 2006-2012

Which is the correct version to use?  If it is 0.94, why isn't this version in Pypi?  Why did the version number drop from 20.0 to 0.94?  If it is 20.0, why is this repo out of date?

**Comment by ViViDboarder** [comment]
Hey, I know I'm late to the game here, but is this version not on PyPi? From what I can see the super old fork is still up there. If I wanted to build a module that uses Beatbox, what is the best way to include it? Thanks!

**Comment by idbentley** [comment]
My solution was to fork the repository. I don't maintain it anymore, but checkout pyforce in pypi.

**Comment by alanjcastonguay** [comment]
I do, and the pypi package of pyforce should be up to date.
